STAT_NAMES: dict[str, str] = {
                'air_damage_percent':'aDamPct',
                'air_damage_raw':'aDamRaw',
                'air_def':'aDef',
                'air_def_percent':'aDefPct',
                'air_melee_damage_percent':'aMdPct',
                'air_melee_damage_raw':'aMdRaw',
                'air_spell_damage_percent':'aSdPct',
                'air_spell_damage_raw':'aSdRaw',
                'agility':'agi',
                'agility_requirement':'agiReq',
                'allow_craftsman':'allowCraftsman',
                'attacktier':'atkTier',
                'average_dps':'averageDps',
                'critical_damage_percent':'critDamPct',
                'damage_percent':'damPct',
                'damage_raw':'damRaw',
                'defense':'def',
                'defense_requirement':'defReq',
                'dexterity':'dex',
                'dexterity_requirement':'dexReq',
                'elemental_damage_percent':'eDamPct',
                'elemental_damage_raw':'eDamRaw',
                'elemental_defense':'eDef',
                'elemental_defense_percent':'eDefPct',
                'elemental_melee_damage_percent':'eMdPct',
                'elemental_melee_damage_raw':'eMdRaw',
                'elemental_spell_damage_percent':'eSdPct',
                'elemental_spell_damage_raw':'eSdRaw',
                'elemental_steal':'eSteal',
                'exploding_damage':'expd',
                'fire_damage_percent':'fDamPct',
                'fire_damage_raw':'fDamRaw',
                'fire_defense':'fDef',
                'fire_defense_percent':'fDefPct',
                'fire_melee_damage_percent':'fMdPct',
                'fire_melee_damage_raw':'fMdRaw',
                'fire_spell_damage_percent':'fSdPct',
                'fire_spell_damage_raw':'fSdRaw',
                'fixed_id':'fixID',
                'heal_percent':'healPct',
                'hp':'hp',
                'hp_bonus':'hpBonus',
                'hp_regen_percent':'hprPct',
                'hp_regen_raw':'hprRaw',
                'id':'id',
                'intelligence':'int',
                'intelligence_requirement':'intReq',
                'jump_height':'jh',
                'knockback':'kb',
                'level_bonus':'lb',
                'life_steal':'ls',
                'level':'lvl',
                'main_attack_range':'mainAttackRange',
                'max_mana':'maxMana',
                'melee_damage_percent':'mdPct',
                'melee_damage_raw':'mdRaw',
                'mana_regen':'mr',
                'mana_steal':'ms',
                'neutral_damage_percent':'nDamPct',
                'neutral_damage_raw':'nDamRaw',
                'neutral_melee_damage_percent':'nMdPct',
                'neutral_melee_damage_raw':'nMdRaw',
                'neutral_spell_damage_percent':'nSdPct',
                'neutral_spell_damage_raw':'nSdRaw',
                'persistent':'persistent',
                'poison':'poison',
                'raw_damage_percent':'rDamPct',
                'raw_damage_raw':'rDamRaw',
                'raw_defense_percent':'rDefPct',
                'raw_melee_damage_percent':'rMdPct',
                'raw_melee_damage_raw':'rMdRaw',
                'raw_spell_damage_percent':'rSdPct',
                'raw_spell_damage_raw':'rSdRaw',
                'reflection':'ref',
                'spell_damage_percent':'sdPct',
                'spell_damage_raw':'sdRaw',
                'slots':'slots',
                'slow_enemy':'slowEnemy',
                'spell_cost_percent_1':'spPct1',
                'spell_cost_percent_2':'spPct2',
                'spell_cost_percent_3':'spPct3',
                'spell_cost_percent_4':'spPct4',
                'spell_cost_raw_1':'spRaw1',
                'spell_cost_raw_2':'spRaw2',
                'spell_cost_raw_3':'spRaw3',
                'spell_cost_raw_4':'spRaw4',
                'walk_speed':'spd',
                'sprint':'sprint',
                'sprint_regen':'sprintReg',
                'strength':'str',
                'strength_requirement':'strReq',
                'thunder_damage_percent':'tDamPct',
                'thunder_damage_raw':'tDamRaw',
                'thunder_defense':'tDef',
                'thunder_defense_percent':'tDefPct',
                'thunder_melee_damage_percent':'tMdPct',
                'thunder_melee_damage_raw':'tMdRaw',
                'thunder_spell_damage_percent':'tSdPct',
                'thunder_spell_damage_raw':'tSdRaw',
                'thorns':'thorns',
                'water_damage_percent':'wDamPct',
                'water_damage_raw':'wDamRaw',
                'water_defense':'wDef',
                'water_defense_percent':'wDefPct',
                'water_spell_damage_percent':'wSdPct',
                'water_spell_damage_raw':'wSdRaw',
                'weaken_enemy':'weakenEnemy',
                'xp_bonus':'xpb'}


STAT_INDICES: dict[str, int] = {
                'air_damage_percent': 0,
                'air_damage_raw': 1,
                'air_def': 2,
                'air_def_percent': 3,
                'air_melee_damage_percent': 4,
                'air_melee_damage_raw': 5,
                'air_spell_damage_percent': 6,
                'air_spell_damage_raw': 7,
                'agility': 8,
                'agility_requirement': 9,
                'allow_craftsman': 10,
                'attacktier': 11,
                'average_dps': 12,
                'critical_damage_percent': 13,
                'damage_percent': 14,
                'damage_raw': 15,
                'defense': 16,
                'defense_requirement': 17,
                'dexterity': 18,
                'dexterity_requirement': 19,
                'elemental_damage_percent': 20,
                'elemental_damage_raw': 21,
                'elemental_defense': 22,
                'elemental_defense_percent': 23,
                'elemental_melee_damage_percent': 24,
                'elemental_melee_damage_raw': 25,
                'elemental_spell_damage_percent': 26,
                'elemental_spell_damage_raw': 27,
                'elemental_steal': 28,
                'exploding_damage': 29,
                'fire_damage_percent': 30,
                'fire_damage_raw': 31,
                'fire_defense': 32,
                'fire_defense_percent': 33,
                'fire_melee_damage_percent': 34,
                'fire_melee_damage_raw': 35,
                'fire_spell_damage_percent': 36,
                'fire_spell_damage_raw': 37,
                'fixed_id': 38,
                'heal_percent': 39,
                'hp': 40,
                'hp_bonus': 41,
                'hp_regen_percent': 42,
                'hp_regen_raw': 43,
                'id': 44,
                'intelligence': 45,
                'intelligence_requirement': 46,
                'jump_height': 47,
                'knockback': 48,
                'level': 49,
                'level_bonus': 50,
                'life_steal': 51,
                'main_attack_range': 52,
                'mana_regen': 53,
                'mana_steal': 54,
                'max_mana': 55,
                'melee_damage_percent': 56,
                'melee_damage_raw': 57,
                'neutral_damage_percent': 58,
                'neutral_damage_raw': 59,
                'neutral_melee_damage_percent': 60,
                'neutral_melee_damage_raw': 61,
                'neutral_spell_damage_percent': 62,
                'neutral_spell_damage_raw': 63,
                'persistent': 64,
                'poison': 65,
                'raw_damage_percent': 66,
                'raw_damage_raw': 67,
                'raw_defense_percent': 68,
                'raw_melee_damage_percent': 69,
                'raw_melee_damage_raw': 70,
                'raw_spell_damage_percent': 71,
                'raw_spell_damage_raw': 72,
                'reflection': 73,
                'slots': 74,
                'slow_enemy': 75,
                'spell_cost_percent_1': 76,
                'spell_cost_percent_2': 77,
                'spell_cost_percent_3': 78,
                'spell_cost_percent_4': 79,
                'spell_cost_raw_1': 80,
                'spell_cost_raw_2': 81,
                'spell_cost_raw_3': 82,
                'spell_cost_raw_4': 83,
                'spell_damage_percent': 84,
                'spell_damage_raw': 85,
                'sprint': 86,
                'sprint_regen': 87,
                'strength': 88,
                'strength_requirement': 89,
                'thunder_damage_percent': 90,
                'thunder_damage_raw': 91,
                'thunder_defense': 92,
                'thunder_defense_percent': 93,
                'thunder_melee_damage_percent': 94,
                'thunder_melee_damage_raw': 95,
                'thunder_spell_damage_percent': 96,
                'thunder_spell_damage_raw': 97,
                'thorns': 98,
                'walk_speed': 99,
                'water_damage_percent': 100,
                'water_damage_raw': 101,
                'water_defense': 102,
                'water_defense_percent': 103,
                'water_spell_damage_percent': 104,
                'water_spell_damage_raw': 105,
                'weaken_enemy': 106,
                'xp_bonus': 107
}

